sclorg/redis-container

3.2/Dockerfile, 3.2/Dockerfile.rhel7, 3.2/README.md, 3.2/root/usr/bin/run-redis, 3.2/root/usr/libexec/container-setup, 3.2/root/usr/share/container-scripts/redis/common.sh, 3.2/test/run
It is better, so .bashrc is not overwritten when mounting a volume
and datadir is not spoiled by any other files that might be stored
into redis' home dir that is /var/lib/redis.
This update also enhances documentation.
=> Change datadir to /var/lib/redis/data

3.2/cccp.yml
This is for the purpose of building these containers on
the CentOS Container Pipeline.
=> Added cccp.yml file for centos container pipeline.

3.2/Dockerfile, 3.2/root/usr/bin/run-redis, 3.2/root/usr/share/container-scripts/redis/common.sh
Seems required to connect from outside the container when no password is set, to avoid:
```
$ redis-cli 
127.0.0.1:6379> info
DENIED Redis is running in protected mode because protected mode is enabled, no bind address was
specified, no authentication password is requested to clients. In this mode connections are only accepted
from the loopback interface. If you want to connect from external computers to Redis you may adopt one of
the following solutions: 
1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback
interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is
not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 
2) Alternatively you can just …
```
=> Protected mode

3.2/test/run
After upgrade from docker 1.10 to docker 1.12 `assert_local_access` test started to fail.
So `docker exec $(get_cid "$id") bash -c redis-cli ping` is waiting forever. Quotes or -i is required to make test passing.
=> Fix assert_local_access test

3.2/Dockerfile, 3.2/Dockerfile.fedora, 3.2/Dockerfile.rhel7, 3.2/root/usr/bin/usage, 3.2/root/usr/share/container-scripts/redis/README.md, README.md
Use maintainer label consistently
Few edits in top-level README
Using usage label and command
Remove tables in README, because go-md2man cannot convert them properly
=> Various small documentation related changes

examples/redis-ephemeral-template.json, examples/redis-persistent-template.json
[Replace 'template.openshift.io' with 'openshift.io'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501)
and 
[Remove ' (Persistent)'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86940496)
=> Fix templates according to `openshift/origin`

3.2/Dockerfile
It is not necessary to use testing repo now anymore, all packages are in released repo already.
=> Use released repos only

imagestreams/redis-centos7.json, imagestreams/redis-rhel7.json
This pull request removes a minor typo for all the image stream descriptions.
=> Removing Version Typo from Image Stream Descriptions

test/run-openshift-local-cluster, test/run-openshift-remote-cluster, test/test-lib-redis.sh
This PR combines more changes:
- add image stream test
- adopts new functions refactored in https://github.com/sclorg/container-common-scripts/pull/155/files
- enables tests to be run in a remote OCP4 cluster
=> Use refactored functions and enable testing in remote OCP4

5/Dockerfile, 5/Dockerfile.fedora, 5/Dockerfile.rhel7, 5/Dockerfile.rhel8
In our environment, we have a redis sidecar container in each of our pods, using a unix domain socket shared amongst multiple containers.
To deal with the arbitrary UID problem, we typically give +rw access to the "root" group. However, we ran into issues with the Redis container, since the user only belongs to the "redis" group. This PR fixes that problem for us.
=> Append "redis" group rather than making it exclusive

5/Dockerfile, 5/root/usr/share/container-scripts/redis/README.md, 6/Dockerfile, 6/root/usr/bin/run-redis, 6/root/usr/libexec/container-setup, 6/root/usr/share/container-scripts/redis/README.md, 6/root/usr/share/container-scripts/redis/common.sh, README.md, imagestreams/redis-centos.json, test/run-openshift-local-cluster, test/test-lib-redis.sh
This commit uses Quay.io register instead of Docker.io
Fixes: https://github.com/sclorg/redis-container/issues/69
=> Support redis-container on Quay.io

imagestreams/redis-centos.json
Use quay.io in imagestreams to avoid hitting ratelimit on dockerhub
=> imagestream: prefer quay.io image

test/run-openshift-remote-cluster, test/test-lib-redis.sh, test/test-lib-remote-openshift.sh
This pull request adds support to test redis-container under OpenShift 4 Jenkins CI .
It is easy, just add `[test-openshift-4]` comment into PR.
=> upport testing redis-container under OpenShift 4 environment

examples/redis-ephemeral-template.json, examples/redis-persistent-template.json, imagestreams/redis-centos.json, imagestreams/redis-rhel-aarch64.json, imagestreams/redis-rhel.json
- Update imagestreams for RHSCL 3.8
- Update examples to redis 6
- Use groupified apiVersion
=> Update imagestreams for RHSCL 3.8

6/Dockerfile, 6/Dockerfile.fedora, 6/Dockerfile.rhel7, 6/Dockerfile.rhel8, 6/root/usr/bin/run-redis, 6/root/usr/libexec/container-setup, 6/root/usr/share/container-scripts/redis/common.sh
This commit allows building redis-6 on CentOS7, RHEL7, and RHEL8.
The configuration file on Fedora has a different location than on the others.
Fedora configuration file is store in location: /etc/redis/redis.conf
For the rest supported OS configuration file location is: /etc/redis.conf
The scripts: `6/root/usr/bin/run-redis`, ` 6/root/usr/libexec/container-setup`, and ` 6/root/usr/share/container-scripts/redis/common.sh` have been modified with proper location.
=> Enable testing redis 6 for RHEL7 and RHEL8

.github/workflows/docker-tests.yml
This pull request adds support for testing `redis-container` in C9S environment.
The tests will be filed as a separate pull request.
=> Add support for testing redis-container in C9S

imagestreams/redis-rhel-aarch64.json, imagestreams/redis-rhel.json
There do not seem to be any Redis 6 CentOS container builds though,
so 5 remains the only (albeit unmaintained) choice for OKD.
RHEL 7 Redis 5 retirement: Jun 2022
RHEL 8 Redis 5 retirement: May 2022
https://access.redhat.com/support/policy/updates/rhscl-rhel7
https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle
=> Remove Redis 5 RHEL imagestreams, add RHEL 9 imagestreams

test/run
In previous tests I see only results for:
```
[PASSED] for 'run_container_creation_tests' 
[PASSED] for 'run_tests_no_root' 
[PASSED] for 'run_tests_no_pass' 
[PASSED] for 'run_tests_no_pass_altuid' 
[PASSED] for 'run_tests_no_root_altuid' 
```
Now all available tests are being executed:
```
[PASSED] for 'redis_tests' run_container_creation_tests (00:00:00)
[PASSED] for 'redis_tests' run_tests_no_root (00:00:04)
[PASSED] for 'redis_tests' run_tests_no_pass (00:00:03)
[PASSED] for 'redis_tests' run_tests_no_pass_altuid (00:00:03)
[PASSED] for 'redis_tests' run_tests_no_root_altuid (00:00:04)
[FAILED] for 'redis_tests' run_change_password_test (00:00:02)
[PASSED] for 'redis_tests' run_doc_test (00:00:01)
```
However, I am not sure, why the `run_change_password_test` fails as it seems like …
=> Use generic run tests

.github/workflows/build-and-push.yml, 7/Dockerfile.fedora
=> deprecate redis6 Fedora image + move redis7 Fedora image to f38 base

test/run
**Warning: this requires https://github.com/sclorg/container-common-scripts/pull/238 to be merged first.**
This also solves the false positive problem that has been in the test script:
The  made the test stopped at the end of run_change_password_test
test, when the code actually expected the old password to be working
(despite the comment said otherwise).
It effectively skipped the last test (documentation check) and what is worse,
the test was still reported as passed, despite the test run_change_password_test
failed (false positive).
The changes in the run_change_password_test test, avoiding usage of errexit,
and usage of the common functions should avoid happening this again.
=> Use test-lib.sh for common test functions

6/root/usr/share/container-scripts/redis/README.md, 6/root/usr/share/container-scripts/redis/common.sh, 6/root/usr/share/container-scripts/redis/post-init.sh, 7/root/usr/share/container-scripts/redis/README.md, 7/root/usr/share/container-scripts/redis/common.sh, 7/root/usr/share/container-scripts/redis/post-init.sh, test/run
Add support for adding bind to /etc/redis.conf
by BIND_ADDRESS variable
Closes #128
=> Fixes: #128 Add support for adding bind to /etc/redis.conf

test/run-openshift-remote-cluster, test/test-lib-redis.sh
This pull request adds support for testing the latest imagestreams for redis container.
=> Add support for testing the latest imagestreams

examples/redis-ephemeral-template.json, examples/redis-persistent-template.json, test/test-lib-redis.sh
Migration from DeploymentConfig to Deployment
For more information see
https://docs.openshift.com/container-platform/4.12/applications/deployments/what-deployments-are.html
Since OpenShift 4.14 DeploymentConfigs are deprecated. https://access.redhat.com/articles/7041372
Use officially released image for testing
=> Migrate from DeploymentConfig to Deployment

test/check_imagestreams.py, test/show_all_imagestreams.py
This pull request only adds show_all_imagestreams.py so it is working.
The file `show_all_imagestreams.py` shows all available imagestreams for this container, that are specified
in the directory `imagestreams`.
The example output will be seen in the next comment.
=> Add file show_all_imagestreams.py from container-common-scripts

.github/workflows/openshift-pytests.yml
Add GitHub action for testing container by PyTest in OpenShift 4
The GitHub action is similar like here:
https://github.com/sclorg/httpd-container/blob/master/.github/workflows/openshift-pytests.yml or https://github.com/sclorg/mariadb-container/blob/master/.github/workflows/openshift-pytests.yml sclorg/mysql-container#369
And the tests are triggered properly.
=> Add GitHub action for testing container by PyTest in OpenShift 4

test/run-openshift-pytest, test/test_redis_imagestream.py, test/test_redis_imagestream_template.py, test/test_redis_latest_imagestreams.py, test/test_redis_template.py
This pull request adds support for testing mariadb-container by PyTest.
=> Add Pytests for testing redis in OpenShift 4

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml, 6/root/usr/share/container-scripts/redis/README.md, 7/root/usr/share/container-scripts/redis/README.md, README.md, imagestreams/imagestreams.yaml, imagestreams/redis-rhel-aarch64.json, imagestreams/redis-rhel.json, test/run-openshift-remote-cluster, test/test-lib-redis.sh
This pull request deprecates RHEL7 and updates README's
=> Remove RHEL-7 - EOL in June 2024

test/test_redis_helm_chart_imagestreams.py, test/test_redis_helm_chart_template.py
This pull request enables testing Helm charts stored in https://github.com/sclorg/helm-charts.
=> Testing Helm charts in redis-container

test/test_redis_shared_helm_imagestreams.py, test/test_redis_shared_helm_template.py
We use prefix `redhat-` in helm charts
=> Fix helm charts name. prefix `redhat-` is needed.
