- 3.2/Dockerfile
- 3.2/Dockerfile.rhel7
- 3.2/README.md
- 3.2/root/usr/share/container-scripts/redis/common.sh
- hack/common.mk
We also may start using packages from CentOS buildlogs
New RH labels added
> Several changes from downstream

- 3.2/test/run
Also make the test output more readable by removing unnecessary output
> Test also scenario without password

- 3.2/Dockerfile.fedora
- 3.2/root/usr/libexec/container-setup
This is also base for https://bugzilla.redhat.com/show_bug.cgi?id=1431528
> Provide Fedora Dockerfile

- examples/redis-ephemeral-template.json
- examples/redis-persistent-template.json
- test/test-lib-openshift.sh
[Changes Info](https://github.com/sclorg/s2i-python-container/pull/218#issuecomment-335276731)
> Add templates from openshift/origin.

- 3.2/Dockerfile
- 3.2/Dockerfile.rhel7
Does not introduce any source to image functionality yet.
> Layer all versions on s2i-core

- 3.2/Dockerfile.fedora
A separate PR for Fedora Dockerfile, so we can merge #24.
> Base Fedora variant on F27 as well

- imagestreams/redis-rhel7-ppc64le.json
- imagestreams/redis-rhel7-s390x.json
Similar PR to sclorg/mariadb-container#115
> Add imagestream file for s390x and ppc64le

- 5/Dockerfile
- 5/Dockerfile.fedora
- 5/Dockerfile.rhel7
- 5/Dockerfile.rhel8
The previous comment did not correspond with the actual status.
> Fix UID explanation and add the described fix

- test/examples
- test/imagestreams
> Add symlinks for examples and imagestreams

- .github/workflows/build-and-push.yml
> Add support for pushing image into quay.io registry

- .github/workflows/build-and-push.yml
> Versions are hardcoded

- .github/workflows/build-and-push.yml
> Fix missing $ in github-push

- .github/workflows/docker-tests.yml
> Fix yml order

- .github/workflows/docker-tests.yml
> Let's use only one job

- .github/workflows/docker-tests.yml
> Let's use GitHub environment for storing

- .github/workflows/openshift-tests.yml
- test/run-openshift-remote-cluster
First set variable and then check oc status
> Fix openshift4 tests

- test/test-lib-redis.sh
This pull request updates container-common-scripts
and fix image stream template tests by adding the tag into the version.
> Fix openshift tests for redis container

- .github/workflows/build-and-push.yml
- 6/Dockerfile.c9s
This pull request adds support for building, testing `redis-container` in C9S environment.
It adds 5/.exclude-c9s file to not build and test container in C9S for version 5
Dockerfile.c9s file is added to version 6 and supports building `redis-container` in C9S.
> Support build and test redis container in C9S

- .github/workflows/container-tests.yml
> Use Testing Farm as GitHub Action

- .github/workflows/build-and-push.yml
- 6/Dockerfile.fedora
- README.md
This pull request adds support for building and pushing
`redis-6` image to `quay.io/fedora/redis-6-fedora` repository.
> Support quayio fedora

- .github/workflows/build-and-push.yml
- 5/Dockerfile.c8s
- 6/Dockerfile.c8s
- 6/root/usr/share/container-scripts/redis/README.md
- README.md
This pull request adds support for CentOS Stream 8.
This pull request is blocked by https://github.com/sclorg/s2i-base-container/pull/246 and https://github.com/sclorg/container-common-scripts/pull/246
> Support c8s

- .github/workflows/container-tests.yml
> Use Fedora-latest compose

- .github/workflows/openshift-tests.yml
> Use Testing Farm as GitHub Action for redis-container

- imagestreams/redis-rhel-aarch64.json
- imagestreams/redis-rhel.json
> [2/2] Deprecate version Redis 5 for RHEL-8

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
> Use RHEL-8.6-Nightly for testing

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
> Testing single versions for container and openshift tests

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
Add support for testing redis-7 by GitHub Actions
This pull request is needed by PR https://github.com/sclorg/redis-container/pull/132
> Add support for testing redis-7 by GitHub Actions

- 6/Dockerfile.c8s
- 6/Dockerfile.c9s
- 6/Dockerfile.fedora
- 6/Dockerfile.rhel8
- 6/Dockerfile.rhel9
- 7/Dockerfile.c8s
- 7/Dockerfile.c9s
- 7/Dockerfile.fedora
- 7/Dockerfile.rhel8
- 7/Dockerfile.rhel9
> Check version of the just-installed redis

- .github/workflows/build-and-push.yml
- 7/Dockerfile.c9s
- 7/Dockerfile.rhel9
Enable building and testing redis-7 for C9S and RHEL9.
For RHEL9 devel-repo is used.
> Enable building and testing redis-7 for C9S and RHEL9.

- imagestreams/redis-rhel-aarch64.json
- imagestreams/redis-rhel.json
- test/test-lib-redis.sh
Skipping testing imagestreams 7. It is not generally available yet
> Skipping testing imagestreams 7. It is not generally available yet

- .github/workflows/build-and-push.yml
- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
- 6/root/usr/share/container-scripts/redis/README.md
- 7/root/usr/share/container-scripts/redis/README.md
- README.md
> Deprecate c8s

- .github/workflows/openshift-tests.yml
- imagestreams/imagestreams.yaml
- imagestreams/redis-centos.json
- imagestreams/redis-rhel-aarch64.json
- imagestreams/redis-rhel.json
- test/test-lib-redis.sh
No custom tag is needed, as far as I know.
> Add imagestream generator

- test/test_redis_imagestream.py
- test/test_redis_imagestream_template.py
- test/test_redis_latest_imagestreams.py
- test/test_redis_template.py
> Use VERSION instead of SINGLE_VERSION, like we do in whole org

- .github/workflows/container-tests.yml
This pull request enables testing redis-container for C10S version.
> Allow testing CentOS Stream 10 for redis

- test/test_redis_helm_chart_imagestreams.py
> Do not test CentOS Stream imagestreams in Helm charts

- .github/workflows/auto-merge-on-demand.yml
Only updates container common scripts
> Update container-common-scripts to the latest
